# -*- coding: utf-8 -*-
"""CS_Project_Text_Adventure115.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3XNFTDNulmMsnjkdnBpBfRW0tmDKURc

# Classes
"""

#Hello World
class Weapon:
    def __init__(self, name, damage, price):
        self.name = name
        self.damage = damage
        self.price = price

    def __str__(self):
        return f"{self.name} (Damage: {self.damage}, Price: ${self.price})"

class Player:
    def __init__(self, name, starting_money=100, starting_health=100):
        self.name = name
        self.money = starting_money
        self.inventory = []
        self.max_health = starting_health
        self.health = starting_health
        self.damage_boost = 0
        self.potions = []

    def display_status(self):
        print(f"\n{self.name}'s Status:")
        print(f"  Money: ${self.money}")
        print(f"  Inventory: {[weapon.name for weapon in self.inventory] or 'Empty'}")
        print(f"  Health: {self.health}/{self.max_health}")
        print(f"  Damage Boost: {self.damage_boost}")
        print(f"  Potions: {[potion.name for potion in self.potions] or 'Empty'}")

    def buy_weapon(self, weapon):
         # Prevent duplicate purchases
      if weapon in self.inventory:
        print(f"You already own {weapon.name}.")
        return

    # Check if player has enough money
      if self.money >= weapon.price:
        self.money -= weapon.price
        self.inventory.append(weapon)

        print(f"{self.name} bought {weapon.name} for ${weapon.price}.")

      else:
        print(f"{self.name} does not have enough money to buy {weapon.name}.")

    def buy_potion(self, potion):

      if self.money >= potion.price:
          self.money -= potion.price
          self.potions.append(potion)

          print(f"{self.name} bought {potion.name}.")

      else:
          print("Not enough money.")

class Monster:
    def __init__(self, name, health, damage, money_drop):
        self.name = name
        self.health = health
        self.damage = damage
        self.money_drop = money_drop

    def __str__(self):
        return f"{self.name} (Health: {self.health}, Damage: {self.damage}, Money Drop: ${self.money_drop})"

    def take_damage(self, amount):
        self.health -= amount
        if self.health < 0:
            self.health = 0
        print(f"{self.name} took {amount} damage! {self.name}'s health: {self.health}")

    def is_defeated(self):
        return self.health <= 0

# Dont forget to balance health and damage, maybe random damage or skip turns?
monster_data = [
    ("Goblin", 50, 5, 20),
    ("Wolf", 80, 8, 35),
    ("Ogre", 100, 10, 50),
    ("Dragon", 150, 18, 100),
    ("Demon King", 250, 30, 200)
]


class Armor:
    def __init__(self, name, defense, price):
        self.name = name
        self.defense = defense
        self.price = price

    def __str__(self):
        return f"{self.name} (Defense: {self.defense}, Price: ${self.price})"

class Potion:
    def __init__(self, name, effect_type, effect_amount, price):
        self.name = name
        self.effect_type = effect_type
        self.effect_amount = effect_amount
        self.price = price

    def __str__(self):
        return f"{self.name} ({self.effect_type}: {self.effect_amount}, Price: ${self.price})"

    def use(self, player):

        # Heal
        if self.effect_type == "heal":
            player.health += self.effect_amount

            if player.health > player.max_health:
                player.health = player.max_health

            print(f"{player.name} healed for {self.effect_amount} HP!")
            print(f"Current Health: {player.health}/{player.max_health}")

        # Damage boost
        elif self.effect_type == "damage":
            player.damage_boost += self.effect_amount

            print(f"{player.name}'s damage increased by {self.effect_amount}!")

        # Max hp
        elif self.effect_type == "max_health":
            player.max_health += self.effect_amount
            player.health += self.effect_amount

            print(f"{player.name}'s max health increased by {self.effect_amount}!")
            print(f"New Max Health: {player.max_health}")

#Weapons, one troll weapon
stone_sling = Weapon("Stone Sling", damage=10, price=15)
dagger = Weapon("Dagger", damage=25, price=40)
short_bow = Weapon("Short Bow", damage=30, price=60)
rusty_sword = Weapon("Rusty Sword", damage=45, price=75)
ultimate_weapon = Weapon("Ultimate Weapon", damage=0, price=100) # Special troll weapon does literaly nothing
#Potions, maybe make damage potions if time left later
small_heal = Potion("Small Healing Potion", "heal", 25, 20)
rage_potion = Potion("Rage Potion", "damage", 10, 35)
health_elixir = Potion("Health Elixir", "max_health", 50, 50)

shop_weapons = [stone_sling, dagger, short_bow, rusty_sword, ultimate_weapon]
shop_potions = [small_heal, rage_potion, health_elixir]

#Shop
def display_shop(weapons, potions):

    print("\n*** Welcome to the Shop! ***")

    print("\nWEAPONS:")
    for i, weapon in enumerate(weapons):
        print(f"{i + 1}. {weapon}")

    potion_start = len(weapons)

    print("\nPOTIONS:")
    for i, potion in enumerate(potions):
        print(f"{potion_start + i + 1}. {potion}")

    print(f"\n0. Exit Shop")


def run_shop(player, shop_weapons, shop_potions):

    while True:

        player.display_status()

        display_shop(shop_weapons, shop_potions)

        try:
            choice = int(input("\nChoose an item to buy: "))

            # Exit shop
            if choice == 0:
                print("\nExiting shop.")
                break

            # Weapon purchases
            elif 1 <= choice <= len(shop_weapons):

                chosen_weapon = shop_weapons[choice - 1]
                player.buy_weapon(chosen_weapon)

            # Potion purchases
            elif len(shop_weapons) < choice <= len(shop_weapons) + len(shop_potions):

                potion_index = choice - len(shop_weapons) - 1
                chosen_potion = shop_potions[potion_index]

                player.buy_potion(chosen_potion)

            else:
                print("Invalid choice.")

        except ValueError:
            print("Please enter a number.")

# Create player
player1 = Player("Hero", starting_money=100)

# Shop
#run_shop(player1, shop_weapons) it works

player1.display_status()

"""### Battle System

 `battle` function
"""

def battle(player, monster):

    print(f"\n*** A wild {monster.name} appears! ***")
    print(f"{player.name} vs. {monster.name}")

    if not player.inventory:
        print(f"{player.name} has no weapons! Cannot fight.")
        print(f"{monster.name} wins the battle!")
        player.health = 0
        print("\n*** Battle End ***")
        return

    while player.health > 0 and not monster.is_defeated():

        print(f"\n*** {player.name}'s Turn ***")
        print(f"{player.name}'s Health: {player.health}/{player.max_health}")
        print(f"{monster.name}'s Health: {monster.health}")

        print("\nChoose an action:")
        print("0. Run Away")

        print("\nWEAPONS:")
        for i, weapon in enumerate(player.inventory):
            print(f"{i + 1}. Attack with {weapon.name}")

        potion_start = len(player.inventory)

        print("\nPOTIONS:")
        if player.potions:
            for i, potion in enumerate(player.potions):
                print(f"{potion_start + i + 1}. Use {potion.name}")
        else:
            print("No potions")

        chosen_weapon = None
        used_potion = False

        while chosen_weapon is None and not used_potion:

            try:
                choice = int(input("\nEnter choice: "))

                if choice == 0:
                    print(f"\n{player.name} ran away from the battle!")
                    print("\n*** Battle End ***")
                    return

                elif 1 <= choice <= len(player.inventory):
                    chosen_weapon = player.inventory[choice - 1]

                elif potion_start < choice <= potion_start + len(player.potions):
                    potion_index = choice - potion_start - 1
                    chosen_potion = player.potions[potion_index]

                    chosen_potion.use(player)

                    # Remove potion after use finally fixed
                    player.potions.remove(chosen_potion)

                    used_potion = True

                else:
                    print("Invalid choice.")

            except ValueError:
                print("Please enter a number.")

        if chosen_weapon is not None:
            print(f"\n{player.name} attacks with {chosen_weapon.name}!")

            total_damage = chosen_weapon.damage + player.damage_boost
            monster.take_damage(total_damage)

            if monster.is_defeated(): #Bug where battle ends after one turn no matter the health
                print(f"\n{monster.name} has been defeated!")
                print(f"{player.name} wins the battle!")

                player.money += monster.money_drop
                print(f"{player.name} earned ${monster.money_drop}!")

                break
#Bug was fixed
        print(f"\n*** {monster.name}'s Turn ***")

        player.health -= monster.damage

        print(f"{monster.name} attacks!")
        print(f"{player.name} took {monster.damage} damage!")
        print(f"{player.name}'s remaining health: {player.health}")

        if player.health <= 0:
            print(f"\n{player.name} has been defeated!")
            print(f"{monster.name} wins the battle!")
            break

    print("\n*** Battle End ***")

"""### Example Battle

currently bugged after shop system added
"""

# Start the battle
battle(player1, Monster("Goblin", 50, 5, 20))

# Display final status
player1.display_status()

# Main game
def start_game():

    print("\n***********************************")
    print("        MONSTER BATTLE RPG")
    print("***********************************")

    print("\nWelcome, Player!")

    print("""
Game Description:
*****************
Defeat all five monsters to win the game.

Before battles, visit the shop to buy:
- Weapons
- Potions to heal or boost your stats

Each monster becomes stronger and drops more money.

Use your money wisely and survive all five battles!
""")

    input("Press Enter to begin your adventure...")

    #Player maybe custom names?
    player1 = Player("Hero", starting_money=100)

    # Monster fight list switch to list when you can
    monster_list = [
        Monster("Goblin", 50, 5, 20),
        Monster("Wolf", 80, 8, 35),
        Monster("Ogre", 100, 10, 50),
        Monster("Dragon", 150, 18, 100),
        Monster("Demon King", 250, 30, 200)
    ]

    # Main game
    for i, data in enumerate(monster_data):

        monster = Monster(data[0], data[1], data[2], data[3])

        print(f"\n********** ROUND {i + 1} **********")

        # Heal player before each round
        player1.health = player1.max_health

        # Shop phase
        print("\nVisit the shop before battle!")
        run_shop(player1, shop_weapons, shop_potions)

        # Battle phase
        battle(player1, monster)

        # Check for death
        if player1.health <= 0:
            print("\nGAME OVER")
            return

        print(f"\n{player1.name} defeated {monster.name}!")

    print("\n***********************************")
    print("CONGRATULATIONS!")
    print("You defeated all five monsters!")
    print("***********************************")


# START MENU

while True:

    print("\n********** MAIN MENU **********")
    print("1. Start Game")
    print("0. Exit")

    choice = input("\nEnter choice: ")

    if choice == "1":
        start_game()

    elif choice == "0":
        print("\nThanks for playing!")
        break

    else:
        print("Invalid choice.")